version: "3.8"
services:
  juice-shop:
    image: bkimminich/juice-shop:latest
    ports:
      - "3000:3000"
  trivy-scanner:
    image: aquasec/trivy:v0.46.1
    depends_on:
      - juice-shop
    volumes:
      - ./reports:/reports
      - ./scripts:/scripts
    entrypoint: ["/scripts/scan.sh"]
  inspec-tester:
    build:
      context: .
      dockerfile: Dockerfile.inspec
    depends_on:
      - juice-shop
    volumes:
      - ./reports:/reports
    entrypoint: ["/scripts/compliance.sh"]
